# Change these first
owner: abujagonda # Your GitHub organization or username, where this repository lives
repo: statusw # The name of this repository

sites:
  - name: One Healthcare ID
    url: https://identity.onehealthcareid.com/app/index.html
  - name: Gov ID
    url: https://identity.optumgovid.com/app/index.html

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: abujagonda.github.io
  baseUrl: /statusw
  theme: dark
  logoUrl: https://raw.githubusercontent.com/abujagonda/statusw/master/assets/hcp-light-horizontal.svg
  faviconSvg: https://raw.githubusercontent.com/abujagonda/statusw/master/assets/hcp-light-horizontal.svg
  name: Monitor
  introTitle: "**Aikyam Identity Platform Status**"
  introMessage: This is a consolidated status page which uses **real-time** monitoring data.
  navbar:
    - title: Status
      href: /statusw
    - title: Docs
      href: http://glowing-carnival-8kpr6q4.pages.github.io/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
